CREATE DATABASE CIRT;
USE CIRT;

CREATE TABLE USERS(
    ROLE ENUM('Reviewer','Author','Viewer'),
    F_NAME VARCHAR(15) NOT NULL,
    L_NAME VARCHAR(15) NOT NULL,
    ID INT PRIMARY KEY
);

CREATE TABLE ARTICLE(
    PDF_PATH VARCHAR(50) PRIMARY KEY,
    AUTHOR_ID INT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(ID),
    STATUS ENUM('Sent','Under Review', 'Approved', 'Declined'),
    TYPE ENUM('Article', 'Journal', 'Poster','Paper')
);

CREATE TABLE KEYWORDS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_PATH VARCHAR(50),
    KEYWORD VARCHAR(50) NOT NULL,
    FOREIGN KEY (ARTICLE_PATH) REFERENCES ARTICLE(PDF_PATH)
);

CREATE TABLE SAVES(
    SAVE_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    ARTICLE_PATH VARCHAR(50),
    FOREIGN KEY(ARTICLE_PATH) REFERENCES ARTICLE(PDF_PATH)
);