[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_HOST_URL = "0.0.0.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["public/**"]

[images]
  remote_images = [
    "https://www.zotero.org/static/images/icons/zotero-icon-32.png",
    "https://www.mendeley.com/ui/assets/images/mendeley-logo.svg"
  ]
