[build]
  base = "utampa-cirt"
  command = "npx prisma generate && npm run build"
  publish = "build"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://cirtdb.netlify.app"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"